version: "3.8"

services:
  strapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: abele_obsidian_api
    image: abele-obsidian-api
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    ports:
      - "1340:1337"
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    command: npm run dev
    restart: unless-stopped
    networks:
      - abele_obsidian_net
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: abele-obsidian-redis
    ports:
      - "6340:6379"
    volumes:
      - abele_obsidian_redis_data:/data
    restart: unless-stopped
    networks:
      - abele_obsidian_net

networks:
  abele_obsidian_net:
    driver: bridge

volumes:
  abele_obsidian_redis_data:

