version: "3.8"

services:
  strapi:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: abele_obsidian_api
    image: abele-obsidian-api
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    ports:
      - "1340:1337"
    volumes:
      - ./:/opt/app
    working_dir: /opt/app
    command: npm run dev
    restart: unless-stopped
    networks:
      - abele_obsidian_net

networks:
  abele_obsidian_net:
    driver: bridge

